name: Release executable
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    name: Windows Build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout application code
        uses: actions/checkout@v4
        with:
          path: main_app

      - name: Checkout cyclotron.analysis dependency
        uses: actions/checkout@v4
        with:
          repository: lbnl-88ops/cyclotron.analysis
          path: cyclotron.analysis

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pipenv pyinstaller
          pip install ./cyclotron.analysis
          cd main_app
          pipenv install --system --dev
        shell: bash

      - name: Build executable
        run: |
          pyinstaller --noconsole --onefile --icon=trimco.ico trimco.py
        working-directory: main_app 

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./main_app/dist/trimco.exe
          prerelease: ${{ github.ref_name != 'main' }}
